version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::860061945305:role/ecsTaskExecutionRole"
        LoadBalancerInfo:
          ContainerName: "pensioner-details-service-sk"
          ContainerPort: "8000"
        PlatformVersion: "LATEST"